<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260620090000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add managed API keys for read-only schedule access';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE api_key (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, identifier VARCHAR(64) NOT NULL, label VARCHAR(128) NOT NULL, secret_hash VARCHAR(64) NOT NULL, scope VARCHAR(64) NOT NULL, requests_per_minute INT NOT NULL, internal BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, revoked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_used_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_api_key_identifier ON api_key (identifier)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE api_key');
    }
}
