<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260613120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create motorsport schedule tables';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE series (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(32) NOT NULL, name VARCHAR(128) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_series_code ON series (code)');
        $this->addSql('CREATE TABLE season (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, series_id INT NOT NULL, year INT NOT NULL, name VARCHAR(128) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_F0E45BA952783198 ON season (series_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_season_series_year ON season (series_id, year)');
        $this->addSql('CREATE TABLE race_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, season_id INT NOT NULL, round_number INT NOT NULL, name VARCHAR(128) NOT NULL, location VARCHAR(128) NOT NULL, source_url VARCHAR(512) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_14E47F834EC001D1 ON race_event (season_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_event_season_round ON race_event (season_id, round_number)');
        $this->addSql('CREATE TABLE race_session (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, event_id INT NOT NULL, name VARCHAR(64) NOT NULL, starts_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ends_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, source_url VARCHAR(512) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_AE5D1CA71F7E88B ON race_session (event_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_session_event_name ON race_session (event_id, name)');
        $this->addSql('ALTER TABLE season ADD CONSTRAINT FK_F0E45BA952783198 FOREIGN KEY (series_id) REFERENCES series (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE race_event ADD CONSTRAINT FK_14E47F834EC001D1 FOREIGN KEY (season_id) REFERENCES season (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE race_session ADD CONSTRAINT FK_AE5D1CA71F7E88B FOREIGN KEY (event_id) REFERENCES race_event (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE race_session DROP CONSTRAINT FK_AE5D1CA71F7E88B');
        $this->addSql('ALTER TABLE race_event DROP CONSTRAINT FK_14E47F834EC001D1');
        $this->addSql('ALTER TABLE season DROP CONSTRAINT FK_F0E45BA952783198');
        $this->addSql('DROP TABLE race_session');
        $this->addSql('DROP TABLE race_event');
        $this->addSql('DROP TABLE season');
        $this->addSql('DROP TABLE series');
    }
}
